python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 1
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 2
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 3
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 4
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 5
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 6
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 7
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 8
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 9
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 10
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 11
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling regular --case 12
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 1
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 2
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 3
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 4
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 5
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 6
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 7
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 8
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 9
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 10
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 11
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling glass --case 12
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 1
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 2
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 3
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 4
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 5
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 6
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 7
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 8
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 9
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 10
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 11
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling optimized --case 12
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 1
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 2
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 3
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 4
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 5
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 6
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 7
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 8
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 9
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 10
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 11
python waveEquationGenerator.py --nIter 200 --export --exportImages --nx 128 --dt 0.02 --sampling jittered --case 12